enabled: true

fullname: app-evaluation-service
appLabel: app-evaluation-service
replicaCount: 1

strategy:
  maxSurge: 50%
  maxUnavailable: 0

image:
  repository: "903947067217.dkr.ecr.us-east-1.amazonaws.com/togglemaster_evaluation-service"
  tag: "v1.0.0-d07225c"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8004
  targetPort: 8004

ingress:
  enabled: true
  className: nginx
  path: /evaluation-service(/|$)(.*)
  pathType: ImplementationSpecific
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2

envFromSecrets:
  - evaluation-db-secret
  - evaluation-db-secret-host

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

startupProbe:
  httpGet:
    path: /health
    port: 8004
  failureThreshold: 180
  periodSeconds: 1

livenessProbe:
  httpGet:
    path: /health
    port: 8004
  initialDelaySeconds: 15
  periodSeconds: 10

readinessProbe:
  httpGet:
    path: /health
    port: 8004
  initialDelaySeconds: 5
  periodSeconds: 5

autoscaling:
  enabled: true
  name: evaluation-hpa
  minReplicas: 1
  maxReplicas: 3
  averageUtilization: 5
