name: CI Auth Service

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apps/local/1-auth-service/**'
      - 'gitops/auth-service/**'
      - '.github/workflows/auth-service.yml'
      - '.github/actions/**'
  push:
    branches: [main]
    paths:
      - 'apps/local/1-auth-service/**'
      - 'gitops/auth-service/**'
      - '.github/workflows/auth-service.yml'
      - '.github/actions/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run auth-service pipeline
        uses: ./.github/actions/ci-go-service
        with:
          service_name: auth-service
          service_path: apps/local/1-auth-service
          ecr_repository: togglemaster_auth-service
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
