name: CI Auth Service

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apps/local/1-auth-service/**'
      - '.github/workflows/auth-service.yml'
      - '.github/workflows/template-ci-go.yml'
      - '.github/actions/**'
  push:
    branches: [main]
    paths:
      - 'apps/local/1-auth-service/**'
      - '.github/workflows/auth-service.yml'
      - '.github/workflows/template-ci-go.yml'
      - '.github/actions/**'

jobs:
  ci:
    permissions:
      contents: write
    secrets: inherit
    uses: ./.github/workflows/template-ci-go.yml
    with:
      service_name: auth-service
      service_path: apps/local/1-auth-service
      ecr_repository: togglemaster_auth-service
