name: CI Auth Service

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apps/local/1-auth-service/**'
      - '.github/workflows/auth-service.yml'
      - '.github/workflows/template-ci.yml'
      - '.github/actions/**'
  push:
    branches: [main]
    paths:
      - 'apps/local/1-auth-service/**'
      - '.github/workflows/auth-service.yml'
      - '.github/workflows/template-ci.yml'
      - '.github/actions/**'

jobs:
  ci:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/template-ci.yml
    with:
      service_name: auth-service
      service_path: apps/local/1-auth-service
      language: go
      ecr_repository: togglemaster_auth-service
