name: CI Flag Service

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'apps/local/2-flag-service/**'
      - 'gitops/flag-service/**'
      - '.github/workflows/flag-service.yml'
      - '.github/actions/**'
  push:
    branches: [main]
    paths:
      - 'apps/local/2-flag-service/**'
      - 'gitops/flag-service/**'
      - '.github/workflows/flag-service.yml'
      - '.github/actions/**'

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run flag-service pipeline
        uses: ./.github/actions/ci-python-service
        with:
          service_name: flag-service
          service_path: apps/local/2-flag-service
          ecr_repository: togglemaster_flag-service
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
