name: CI Targeting Service

on:
  pull_request:
    paths:
      - 'apps/local/3-targeting-service/**'
      - '.github/workflows/targeting-service.yml'
      - '.github/workflows/template-ci.yml'
      - '.github/actions/**'
  push:
    branches: [main]
    paths:
      - 'apps/local/3-targeting-service/**'
      - '.github/workflows/targeting-service.yml'
      - '.github/workflows/template-ci.yml'
      - '.github/actions/**'

jobs:
  ci:
    permissions:
      contents: write
      id-token: write
    uses: ./.github/workflows/template-ci.yml
    with:
      service_name: targeting-service
      service_path: apps/local/3-targeting-service
      language: python
      ecr_repository: togglemaster_targeting-service
